### ISSUE TITLE
RFM - Fstar

### ISSUE THREAD

**Issue by chantisnake** [chocolatey/chocolatey-package-requests#411] opened 2018-09-05 17:12 UTC
I am deprecating all my packages, you can find previous version of Fstar packages here: https://github.com/chantisnake/chocolateyPackage/tree/master/FStar-choco

**Comment by pauby** [comment] 2018-09-05 17:19
https://chocolatey.org/packages/FStar

**Comment by pauby** [comment] 2018-09-05 19:30
Duplicate of #422 (keeping that one as has GH link to maintainers repo)

**Closed by pauby** 2018-09-05 19:30 UTC
Labels: Duplicate
