### ISSUE TITLE
RFP - IobitUninstaller

### ISSUE THREAD

**Issue by ruchirarya** [chocolatey/chocolatey-package-requests#485] opened 2018-12-08 22:31 UTC
The following famous uninstaller "IobitUninstaller" from www.iobit.com is not available currently.

**Comment by mkevenaar** [comment] 2018-12-08 22:34
Is this the same as mentioned in #119 ?

**Comment by AdmiringWorm** [comment] 2018-12-09 12:43
Duplicate of #119

**Closed by AdmiringWorm** 2018-12-09 12:43 UTC
