### ISSUE TITLE
RFM - geforce-game-ready-driver

### ISSUE THREAD

**Issue by aronovgj** [chocolatey/chocolatey-package-requests#103] opened 2017-02-17 03:58 UTC
Someone should continue this as I don't use an Nvidia GPU anymore. If the package breaks it probably breaks for good until someone takes over. I can not test it.

There is a general package which was discontinued:
https://chocolatey.org/packages/geforce-game-ready-driver
and there are packages for different Windows versions (they exist because Ketarin can't handle 4 different URLs easily):
https://chocolatey.org/packages/geforce-game-ready-driver-win7
https://chocolatey.org/packages/geforce-game-ready-driver-win10

Also note these:
https://github.com/aronovgj/choco-auto/issues/14 
https://chocolatey.org/packages/geforce-game-ready-driver-win10#comment-3156641212

**Comment by Link-Satonaka** [comment] 2017-02-17 15:18
I'll take over if no one else does before I find free time

**Comment by aronovgj** [comment] 2017-02-17 15:19
Let me know when you want me to add you as a maintainter.

**Comment by trajano** [comment] 2017-02-23 02:57
Feel free to grab stuff from my attempt.  https://github.com/trajano/choco-packages/tree/master/geforce-game-ready-driver-win10

**Comment by Link-Satonaka** [comment] 2017-03-09 18:45
OK, I'm ready to take over @aronovgj 

Please give me access to all three packages. I'll be deprecating the OS specific ones, I have restored the general one.

https://github.com/Link-Satonaka/chocopkgs/tree/master/geforce-game-ready-driver

**Comment by trajano** [comment] 2017-03-09 18:58
@Link-Satonaka I like the way you did it the platform switch on yours.

**Comment by aronovgj** [comment] 2017-03-09 19:22
@Link-Satonaka You're in, my Ketarin instance won't push updates of the drivers anymore.

**Comment by aronovgj** [comment] 2017-03-09 20:33
https://github.com/Link-Satonaka/chocopkgs/blob/master/geforce-game-ready-driver/tools/chocolateyInstall.ps1
Does that even work? As far as I remember the exe does not accept parameters. That is why you have to unpack it first.

**Comment by Link-Satonaka** [comment] 2017-03-09 21:01
IIRC we specifically unpacked it to prevent update.core, GeForce experience, and etc from installing.

Since that no longer works as intended, we can go back to simply running the installer.

**Comment by trajano** [comment] 2017-03-09 21:02
@Link-Satonaka the one I have removed GeForce Experience and Update but I haven't tested it on the non-Windows 10 version.

**Comment by Link-Satonaka** [comment] 2017-03-09 21:06
It was reported to me that this would actually uninstall GeForce Experience, which is unacceptable.

**Comment by aronovgj** [comment] 2017-03-09 21:06
https://chocolatey.org/packages/geforce-game-ready-driver/347.52

Thats the first geforce package I pushed. That was before any requests to remove GF Experience. And I still unzipped it first. Pretty sure I did this for a reason.

**Comment by aronovgj** [comment] 2017-03-09 21:10
Regarding @trajano he modifies the config file, instead of just removing the folder. I don't know if that has the same effect of removing GFE.

**Comment by trajano** [comment] 2017-03-09 21:27
All I can tell is on my home machine I do not have GeForce Experience installed which was what I was after.  In addition I found out how to get rid of the other things such as the 3D Vision photo viewer and USB driver as well since I didn't have the hardware either.

In my implementation, there's a `TODO` block which would require some more chocolatey and PowerShell experience to implement,  Namely to provide some extra parameters for the user to add to tweak which parts to add or remove.

**Comment by trajano** [comment] 2017-03-10 14:46
Just checked last night when I got home, no issues installing a new version.  However... I did find that the "uninstall" with the approach I am doing did not work.  Not that I would normally uninstall anyway.

**Comment by aronovgj** [comment] 2017-03-10 15:03
@trajano I am not sure if you entirely get the problem, so just to get it straight

The problem was: 
- You have drivers and GFE installed
- You want to update the drivers
- You remove GFE from the installer by unzipping and then removing the folder where GFE is
- You update the drivers
- Drivers are updated but GFE is being removed

I am not sure if you tested if that also happens modifying the config file. If GFE is installed it should not be removed by doing an update.

**Comment by trajano** [comment] 2017-03-10 15:50
@aronovgj my objective was to have just what is neeeded for the driver installed and avoid any extras such as 3DVision, GFE, NVision, NVUpdate from being loaded.

However, I didn't want to *remove* the folders because I am not exactly sure what would happen, instead I went with the configuration file change approach to simulate what would happen if the user decides to actually pick and choose the parts that they want.

I haven't really done an `update` as of yet.  However, my requirements do vary from just "use whatever comes with the installer" which is valid too.  The problem with whatever comes with the installer will force GeForce Expererience which will in turn manage the updates rather than letting chocolatey do it for me.

**Comment by 07416** [comment] 2017-04-05 15:59
Is it now possible to specify the driver components to install? I always uncheck 3D Vision drivers, Geforce Experience and HD Audio Driver when installing manually.

![2017-04-05 18_54_28-nvidia installer](https://cloud.githubusercontent.com/assets/14923168/24714493/5ba0715e-1a31-11e7-9a18-a81822a6f35e.png)

**Comment by trajano** [comment] 2017-04-05 16:05
@07416 not with the official chocolatey package.  However, I am curious about removing the HD Audio Driver.

**Comment by AdmiringWorm** [comment] 2017-04-06 02:32
closing this as it seem updated packages have been submitted, and they have been approved.

**Closed by AdmiringWorm** 2017-04-06 02:32 UTC

**Comment by Link-Satonaka** [comment] 2017-04-08 05:35
@trajano @07416 You may be interested in my next package-

https://github.com/Link-Satonaka/chocopkgs/blob/master/nvidia-display-driver/tools/chocolateyInstall.ps1

I'll be submitting it after I confer with gitter as to what it should be named.

**Comment by 07416** [comment] 2017-07-20 22:43
@Link-Satonaka [Your package](https://chocolatey.org/packages/nvidia-display-driver) looks great, but can it be safely installed over existing driver installation?

**Comment by aronovgj** [comment] 2017-07-20 22:47
Why wouldn't it?

**Comment by Link-Satonaka** [comment] 2017-07-21 04:28
@07416 The entire point is that it won't install nvidia's bloatware- you'll need to uninstall all that before installing the clean driver.

Fun fact, I discovered that Windows Update will just inherently give you the vanilla display driver. It's a few versions behind current, but honestly that's not really a big deal. Uninstalling all nvidia drivers and letting Windows Update take care of it is perfectly viable.

**Comment by 07416** [comment] 2017-07-25 08:32
I only have the core packages installed - I only asked to confirm.
