### ISSUE TITLE
RFM - DAEMON Tools Lite

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-package-requests#372] opened 2018-06-25 08:20 UTC
https://chocolatey.org/packages/daemontoolslite/4.49.1.20140507

**Comment by mikecole** [comment] 2018-07-20 14:44
I have some concerns about this package.

1) The download are advertised-blocked so the download links are not easily retrieved.

2) The existing version (it's broken anyway) seems to be linked to a Russian file sharing site.

There appears to be a publisher program that one can join that may give us other options here. How are those generally completed? On behalf of the package maintainer or on behalf of Chocolately?

Publisher program: https://www.daemon-tools.cc/partners#publisher-program

**Comment by gep13** [comment] 2018-07-20 18:53
@mikecole hmm, this is a new one on me.  I haven't heard of a publisher program before, so I am really not sure on how to progress with that.  It would be interesting to know if redistributing the binaries would be an option.  I didn't see anything obvious on the site.  Perhaps reaching out to them to answer the question, that might provide a route to take.

**Comment by mikecole** [comment] 2018-07-20 18:59
@gep13 I'll follow up with them. Maybe it will be another fiddler situation where they don't want the package listed.

Should this be marked as Blocked Upstream?

**Comment by AdmiringWorm** [comment] 2018-07-20 19:03
@mikecole I would say yes, it should be marked with `Blocked Upstream`.
As such I've added that label as well.

**Comment by gep13** [comment] 2018-07-20 19:15
@mikecole let us know how you get on, and if you need any assistance.

**Comment by bcurran3** [comment] 2018-07-21 23:35
Dupe of https://github.com/chocolatey/chocolatey-package-requests/issues/238

**Comment by mikecole** [comment] 2018-07-26 13:46
Publisher wishes for this package to be delisted:

Hi Mike, 

Thank you for the detailed reply and explanation.

We are not ready to allow Chocolatey users install DAEMON Tools Lite in silent mode. Please get the existing broken package delisted.

We can offer you to list DAEMON Tools Pro and/or DAEMON Tools Ultra and share partner comission in case of product purchase. Please let me know if you are interested and I will provide you with the details.

**Comment by mikecole** [comment] 2018-07-26 16:19
I de-listed all versions of the package. I think this can be closed.

**Comment by gep13** [comment] 2018-07-26 18:43
@mikecole in addition to the above, I think we need to remove all maintainers from the package as well, that way, no new package versions can be pushed.

**Comment by gep13** [comment] 2018-07-26 18:44
@mikecole I have removed all maintainers from the package.  If the situation changes, we can get this changed as required.

Thanks for following up with this.

**Closed by gep13** 2018-07-26 18:44 UTC
Labels: Blocked Upstream, Status: Available For Maintainer(s)

**Comment by mikecole** [comment] 2018-07-26 19:22
You're welcome.
