### ISSUE TITLE
[RFM] - pycharm professional

### ISSUE THREAD

**Issue by deva1003** [chocolatey/chocolatey-package-requests#176] opened 2017-09-27 11:10 UTC
looking for latest version of pycharm professional to be packaged as chocolatey. Thanks!

**Comment by AdmiringWorm** [comment] 2017-09-27 15:22
I'm guessing this is the package you are looking for?
https://chocolatey.org/packages/Pycharm

Please try reaching out to the maintainer of that package first (look for the `Contact Maintainers` link), before we can open this one up for new maintainers of that package.

Thanks

**Comment by AdmiringWorm** [comment] 2017-09-27 15:23
nvm, I see this is a duplicate of issue #115

**Closed by AdmiringWorm** 2017-09-27 15:23 UTC
Labels: Status: Triage
